#!/bin/bash

set -eo pipefail

usage() {
    echo "usage: $0 [--help] [--push] [--no-cache] [--tag=<tag>] <variant>"
}

BASEDIR=$(realpath $(dirname $0))
VARIANTS=(base jre21)

## options
PUSH=false
OPTS=""
VARIANT=""
TAG="SNAPSHOT"

while [[ $# > 0 ]]; do
    case "$1" in
        --help)
            usage
            exit 0
            ;;
        --push)
            PUSH=true
            shift
            ;;
        --no-cache)
            OPTS="--no-cache"
            shift
            ;;
        --tag)
            shift
            TAG=$1
            if [[ -z ${TAG} ]]; then
                echo "Error: Too few arguments to option '--tag'."
                usage
                exit 1
            fi
            shift
            ;;
        -*)
            echo "Unknown option: $1" >&2
            usage
            exit 1
            ;;
        *)
            if [[ -n ${VARIANT} ]]; then
                echo "Error: Too many arguments."
                usage
                exit 1
            fi
            VARIANT=$1
            shift
            ;;
    esac
done

if ! [[ ${TAG} =~ ^(SNAPSHOT|[0-9]+\.[0-9]+\.[0-9])$ ]]; then
    echo "Error: Invalid TAG format. Use semantic versioning for tags."
    usage
    exit 1
fi

if [[ -z ${VARIANT} ]]; then
    echo "Error: Too few arguments."
    usage
    exit 1
fi

if [[ ! " ${VARIANTS[*]} " =~ " ${VARIANT} " ]]; then
    echo "Error: Unsupported variant: ${VARIANT}"
    exit 1
fi

BUILDDIR=${BASEDIR}/variants/${VARIANT}/build-dir
DOCKERFILE=${BASEDIR}/variants/${VARIANT}/Dockerfile
VERSIONFILE=${BASEDIR}/variants/${VARIANT}/version
PREFIX="${VARIANT#base}"
IMAGE=ghcr.io/installr-io/uci:${PREFIX:+${PREFIX}-}

if [[ $1 == "--no-cache" ]]; then
    shift
    OPTS="--no-cache"
fi

docker build \
    --tag ${IMAGE}${TAG} \
    --tag ${IMAGE}${TAG%.*} \
    --tag ${IMAGE}${TAG%%.*} \
    --file ${DOCKERFILE} \
    --build-arg version=$(cat ${VERSIONFILE}) \
    ${OPTS} \
    ${BUILDDIR}

if [[ ${PUSH} == true ]]; then
    docker image push ${IMAGE}${TAG}
    docker image push ${IMAGE}${TAG%.*}
    docker image push ${IMAGE}${TAG%%.*}
fi
