name: Build UCI

on:
    push:
        branches: ["main"]
    
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Build base
              run: ./build base

            - name: Build jre21
              run: ./build jre21
